// src/react/components/Heatmap/Heatmap.jsx
import React from "react";
import {HeatmapAnimation} from "../../../common/index";

export default class Particle extends React.Component {
  constructor(props) {
    super(props);
  }

  componentDidMount() {
    this.animation = new HeatmapAnimation({
      canvas: this.oCanvas,
      width: this.props.width,
      height: this.props.height,
      number: this.props.number
    });

    this.animation.init()
  }

  render() {
    return (
      <canvas style={this.props.style} ref={canvas => (this.oCanvas = canvas)}>
        您的浏览器不支持Canvas,请使用其他浏览器试试看!
      </canvas>
    );
  }
}

Particle.defaultProps = {
  width: 1080,
  height: 512,
  number: 50,
  style: {
    border: "1px solid lightgray"
  }
};

// src/vue/components/Heatmap/Heatmap.vue
<template>
    <canvas :width="width" :height="height">您的浏览器不支持Canvas,请使用其他浏览器试试看!</canvas>
</template>

<script>
import { HeatmapAnimation } from "../../../common/animation/index";
export default {
  props: {
    width: {
      type: Number,
      default: 300
    },
    height: {
      type: Number,
      default: 300
    },
    number: {
      type: Number,
      default: 30
    }
  },
  mounted() {
    const animation = new HeatmapAnimation({
      width: this.width,
      height: this.height,
      number: this.number,
      canvas: this.$el
    });
    animation.init();
  }
};
</script>

<style>

</style>
